### ISSUE TITLE
Developer Guide feedback

### ISSUE THREAD

**Issue by leowweixiang** [AY2021S1-CS2113T-F11-4/tp#177]
- [x] Recommend the headers also have numbering, e.g. 2. Getting Started, 2.1 Prerequisites. Helps with the longer sections
- [x] Architecture: Minor formatting issue here: "`Main` is single-class component..."
- [x] Architecture: ParserManager, ProjectManager are not shown in the main Architecture Diagram, so instead you can mention them in the Logic component, and say "The `Logic` component does... contains..."
- [x] Logic Component: Recommend bulleting the different `XParser` descriptions.
- [x] Logic Component: The list of subcommands I think is not necessary; or you can link each one to their respective 4.X sections
- [x] Recommend adding separate class diagrams for `Parser` and `Command`, then you can show some methods there. Same for `Project` etc in the Model component, to illustrate what you're saying about "contain necessary information such as"...
- [x] Implementation - Create Project: Minor formatting, separate the link-to-java and description lines
- [x] Implementation - Create Project: Minor typo "Extracts required arguements"
- [x] Implementation - Create Project: Recommend put the sequence diagram in next to the "Implementation"
- [x] Merge "Before execution" and "Implementation" into a usage scenario for the example input instead. "Implementation" isn't the right word for those parts IMO, recommend "usage scenario" instead
- [x] Task: Flesh out the tasks sections the same way as Projects and Sprints
- [x] Storage - Loading data: This is a functionality issue: The program exits when failing to read, but because the data must be human-editable, there is possibility the user can deliberately corrupt the data. You may want to consider that if the data cannot be read, the program should still be able to run, by wiping the corrupted data or something
- [x] **More class diagrams** for Projects, Sprints, Commands, Tasks etc. You have StorageManager in a sequence diagram, calling its methods; so a class diagram of StorageManager with said methods will be good
- [x] Standardise the UML tools used. The formats of Create Project's sequence diagrams and Create Sprint's are different
- [x] User stories: Add in all the user stories you drafted before. Only "See Usage instructions" in v1.0 is weird
- [x] Make sure to fill in the missing sections

**Comment by gmit22** [comment]
* The `parser manager` is a part of the logic component and has been clearly shown in the diagram for `Logic Component`.
* `Project Manager` is a part of the `Model Component` and has already been added.
