### ISSUE TITLE
Standardise package naming convention

### ISSUE THREAD

**Issue by keke101** [AY2021S1-CS2113T-F11-4/tp#23]
We need to come up with a standardised package naming convention.
I suggest all classes to be under the package name of `com.scrumptious`

- Project: `com.scrumptious.project` _members under this package?_
- Sprint: `com.scrumptious.sprint`
- Task: `com.scrumptious.task`
- Storage: `com.scrumptious.storage`
- Parser: `com.scrumptious.parser`
- Exceptions: under its respective type's package. E.g. project's exception is under `com.scrumptious.project.exception`
  - For project-wide's exception: `com.scrumptious.exception`

What do yall think?

**Comment by e0426051** [comment]
sounds ok imo

**Comment by chocomango** [comment]
Yup sounds good, we should standardise. I also suggest we can have data package to hold all the data classes like Project, Sprint, Task.

**Comment by gmit22** [comment]
Sounds good
